Updated README
colinhartigan/valorant-rpc pull request #82
Opened 2021-11-05 22:02 UTC by isaacKenyon

Re-wrote the README to incorporate feedback by @ririxidev and @Soneliem

2021-11-06 07:11 UTC, Soneliem requested changes
As discussed earlier: Replace second discord shield with banner

2021-11-06 07:11 UTC, Soneliem commented on README.md
> + [![Discord][discord-shield]][discord-url]
```suggestion
[![Discord Banner 2][discord-banner]][discord-url]
```

2021-11-06 07:11 UTC, Soneliem commented on README.md
> + Either make an issue or:
```suggestion
 Either make an issue or:  
```

2021-11-06 07:11 UTC, Soneliem commented on README.md
> +
```suggestion
[discord-banner]: https://discordapp.com/api/guilds/860288779558715402/widget.png?style=banner2

```

2021-11-06 07:14 UTC, isaacKenyon commented
> As discussed earlier: Replace second discord shield with banner

Done 👍

2021-11-06 08:04 UTC, ririxidev commented
There are still things that I requested to change before.

2021-11-06 12:46 UTC, isaacKenyon commented
If I have mistakenly left them out, please propose them as a change so I can commit them :)

2021-11-06 19:37 UTC, ririxidev requested changes

2021-11-06 19:37 UTC, ririxidev commented on README.md
> + </a>
no need for <a> tag, if you want to redirect to url, you need to <a> tag every image, not whole stuff

2021-11-06 21:25 UTC, colinhartigan commented
most heated pull request ive ever seen

2022-07-11 17:17 UTC, EMREOYUN approved these changes
In its current status, seems well-made.

2023-01-06 22:43 UTC, merged

2023-01-06 22:46 UTC, Soneliem commented
🎉🎉🎉 Finally, over a year later

2023-01-06 22:47 UTC, colinhartigan commented
i think it's been simmering for long enough now